-- --------------------------------------------------------
--
-- Estrutura da tabela `RESERVAS`
--

CREATE  TABLE `QUADRAS` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NUMERO` INT(6) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `BAIRRO` VARCHAR(45) NOT NULL,
  `LOGRADOURO` VARCHAR(45) NOT NULL
  )
ENGINE = InnoDB;

CREATE TABLE `DIA` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `DIA` DATE NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE `HORARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `HORARIO` TIME NOT NULL
)
ENGINE = InnoDB;
-- --------------------------------------------------------

CREATE TABLE `DIA_HORARIO` (
  `DIA_ID` INT NOT NULL,
  `HORARIO_ID` INT NOT NULL,
  CONSTRAINT fk_dia_horario FOREIGN KEY(`DIA_ID`) REFERENCES DIA (`ID`),
  CONSTRAINT fk_dia_horario1 FOREIGN KEY(`HORARIO_ID`) REFERENCES HORARIO (`ID`)
)
ENGINE = InnoDB;

CREATE TABLE `DIA_QUADRA` (
  `DIA_ID` INT NOT NULL,
  `QUADRA_ID` INT NOT NULL,
  CONSTRAINT fk_dia_quadra FOREIGN KEY(`DIA_ID`) REFERENCES DIA (`ID`),
  CONSTRAINT fk_dia_quadra1 FOREIGN KEY(`QUADRA_ID`) REFERENCES QUADRAS (`ID`)
)
ENGINE = InnoDB;

-- --------------------------------------------------------

--
-- Estrutura da tabela `TIPO_USUARIO`
--

CREATE  TABLE `TIPO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

-- --------------------------------------------------------

--
-- Estrutura da tabela `USUARIO`
--

CREATE TABLE `USUARIO` (
  `SENHA` varchar(45) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(45) NOT NULL,
  `TIPO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


CREATE TABLE `CIDADAO` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOME` VARCHAR(45) NOT NULL,
  `FOTO` MEDIUMBLOB NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  `USUARIO_ID` INT NOT NULL,
  CONSTRAINT fk_usu_cid FOREIGN KEY(`USUARIO_ID`) REFERENCES USUARIO (`ID`)
  )
ENGINE = InnoDB;

-- --------------------------------------------------------

-- Dados da tabela `TIPO`

INSERT INTO TIPO (ID, NOME) VALUES (1, "ADM");
INSERT INTO TIPO (ID, NOME) VALUES (2, "Cidadão");
INSERT INTO TIPO (ID, NOME) VALUES (3, "Zelador");

-- --------------------------------------------------------

-- Dados da tabela `QUADRA`

INSERT INTO QUADRAS (ID, NUMERO, NOME, BAIRRO, LOGRADOURO) VALUES (1, "195", "BEIRA RIO", "JARDIM DOS PASSAROS", "AV. SILVIO GASPARINE");
INSERT INTO QUADRAS (ID, NUMERO, NOME, BAIRRO, LOGRADOURO) VALUES (2, "268", "DECAR", "CENTRO", "RUA ÉRICO DE ABREU SODRÉ");
INSERT INTO QUADRAS (ID, NUMERO, NOME, BAIRRO, LOGRADOURO) VALUES (3, "358", "GRÊMIO", "CENTRO", "AV. DA SAUDADE");

-- --------------------------------------------------------

-- Dados da tabela `DIA`

INSERT INTO DIA (ID, DIA) VALUES (1, "DOMINGO");
INSERT INTO DIA (ID, DIA) VALUES (2, "SEGUNDA-FEIRA");
INSERT INTO DIA (ID, DIA) VALUES (3, "TERÇA-FEIRA");
INSERT INTO DIA (ID, DIA) VALUES (4, "QUARTA-FEIRA");
INSERT INTO DIA (ID, DIA) VALUES (5, "QUINTA-FEIRA");
INSERT INTO DIA (ID, DIA) VALUES (6, "SEXTA-FEIRA");
INSERT INTO DIA (ID, DIA) VALUES (7, "SÁBADO");

-- --------------------------------------------------------

-- Dados da tabela `HORARIO`

INSERT INTO HORARIO (ID, HORARIO) VALUES (1, "DAS 08:00 ÁS 10:00");
INSERT INTO HORARIO (ID, HORARIO) VALUES (2, "DAS 10:00 ÁS 12:00");
INSERT INTO HORARIO (ID, HORARIO) VALUES (3, "DAS 14:00 ÁS 16:00");
INSERT INTO HORARIO (ID, HORARIO) VALUES (4, "DAS 16:00 ÁS 18:00");
INSERT INTO HORARIO (ID, HORARIO) VALUES (5, "DAS 18:00 ÁS 20:00");
INSERT INTO HORARIO (ID, HORARIO) VALUES (6, "DAS 20:00 ÁS 22:00");

-- --------------------------------------------------------